### PR TITLE
Fix update payment session call bad request issue

### LINKED ISSUE #4: 400 Bad Request issue on update payment session call
### Describe the bug
Update Payment Session request call expects the `meta` parameters as required in `/instore/customer/payment/session/{paymentSessionId}` `POST` call as per the wpay swagger spec version 1.0.3. During the creation of the request model `OAIUpdatePaymentSessionRequest` in [OpenApiCustomerPaymentSessionsRepository](https://github.com/w-pay/sdk-wpay-openapi-ios/blob/c975297a140650be12d6d6089fe2f19c1fd43070/VillageWalletSDKOAIClient/Api/OpenApiCustomerPaymentSessionsRepository.swift#L60), only the `data` parameter is set and the `meta` parameter is ignored which will produce a request without the `meta` key. As the server expects the value, it throws a 400 Bad Request error.

### To Reproduce
1. Initiate a request to the POST call using the sdk update payment session function `POST` `/instore/customer/payment/session/{paymentSessionId}`
2. Observe the request parameter using a proxy
3. The `meta` parameter will be missing in the request sent
4. Check the response

***Request created by SDK***
```
{
	"data": {
		"customerInfo": {
			"payload": {
				"rewardsId": "<rewards_number>",
				"usePoints": false
			},
			"schemaId": "<schema_id>"
		}
	}
}
```

***Response***
```
{
	"statusCode": 400,
	"error": "Bad Request",
	"message": "Request failed with status code 400"
}
```

### Expected behaviour
The sdk is expected to pass in a value for the required parameter `meta`.
```
{
	"meta": {},
	"data": {
		"customerInfo": {
			"payload": {
				"usePoints": false,
				"rewardsId": "<rewards_number>"
			},
			"schemaId": "<schema_id>"
		}
	}
}
```

### Versions:
 - XCode version 12.4
 - Swift version 5.5
 - SDK version 4.0.0
 - Open API SDK version 4.0.0
 - iOS version 14.4

### Additional context
The simplest solution to this is to set an empty dictionary to the meta value for `OAIUpdatePaymentSessionRequest`
After init the request model, we could inject an empty dictionary for parameter `meta`
Just add the line of code to [Update payment session function](https://github.com/w-pay/sdk-wpay-openapi-ios/blob/c975297a140650be12d6d6089fe2f19c1fd43070/VillageWalletSDKOAIClient/Api/OpenApiCustomerPaymentSessionsRepository.swift#L62)
```
body.meta = [:]
```
This will pass in an empty dictionary to the request to satisfy the specs.

### PR DESCRIPTION
**Pull request by tomabin**
### Description
Fix update payment session bad request issue
Add the required request parameter `meta` to the POST `/instore/customer/payment/session/{paymentSessionId}` call as per the api spec 1.0.3.

Fixes #4

### CODE REVIEW

File: VillageWalletSDKOAIClient/Api/OpenApiCustomerPaymentSessionsRepository.swift [hunk 1]
```diff
@@ -60,6 +60,7 @@ public class OpenApiCustomerPaymentSessionsRepository: OpenApiClientFactory, Cus
 		let body = OAIUpdatePaymentSessionRequest()
 		body.data = OAIInstoreCustomerPaymentSessionPaymentSessionIdData()
 		body.data.customerInfo = toDynamicPayload(payload: session.customerInfo)
+		body.meta = [:]
```
Comment (kierans) [inline VillageWalletSDKOAIClient/Api/OpenApiCustomerPaymentSessionsRepository.swift:63]: Have you tested this works? There is an `OAIMetaChallenge` class that might be better to use.

Comment (tomabin) [reply VillageWalletSDKOAIClient/Api/OpenApiCustomerPaymentSessionsRepository.swift:63]: Yes, I have tested in UAT env and it works fine. I was passing in an empty dictionary because from the model, it seems like it is expecting and NSDictinoary.
```
@property(nonatomic) NSDictionary<NSString*, NSObject*>* meta;
```
The request which we are sending after modification is as below:
```
{
	"meta": {},
	"data": {
		"customerInfo": {
			"payload": {
				"rewardsId": "<rewards_number>",
				"usePoints": false
			},
			"schemaId": "<schema_id>"
		}
	}
}
```

**Review by kierans — APPROVED** [review]
